### ISSUE TITLE
JSBSIM plugin crashes with clean UE5.0.1 project

### ISSUE THREAD

**Issue by BreakerHUN** [JSBSim-Team/jsbsim#626]
- [x] bug report

**Describe the issue**
The plugin immediately crashes to desktop in UE 5.0.1 when using in clean new project.

**What is the current behavior?**
I download and compile the project, then the referenceapp . It opens perfectly in UE, and can fly around.
Then I copy the whole "Plugin\JSBSimFlightDynamicsModel" to my clean project "MyProject\Plugins"

I can activate the plugin and restart UE.

Then creating a pawn, a static mesh and adding JSBSIMMovement component. The problem starts here.
When I touch the Structural  frame origin propertiy in the component editor, UE immediately crashes to desktop.

or

If I grab the pawn into the world and hit "Play" it immediately crashes.

**What is the expected behavior?**
To integrate into a clean project without crashing.

**What is the motivation / use case for changing the behavior?**
?

**Please tell us about your environment:**
 - OS Windows 10 21H2 [Version 10.0.19044.1706]
 - JSBSim version v1.1.11
 - UE5 Blueprint

**Other information**
I have made a detailed description with screenshots at this link:

https://forums.unrealengine.com/t/jsbsim-plugin-with-ue-5-0-1-crashes-with-new-clean-project/562619

You can find me on Discord as BreakerHUN#3986 to reproduce the error anytime.

**Comment by AlbanBERGERET-Epic** [comment]
Hey guys, 

Sorry about it. Actually, I always edited the Structural Frame origin in the level viewport. There it doesn't crash... 

But indeed, I also reproduced the crash when working in the blueprint editor. This editor is tricky to work in because it doesn't go with the same initialization steps as with the engine viewport. But the good news is that when fixing the issue #637 it fixed this one as a side effect. 

A PR is coming soon with these fixes in one day or so.

**Comment by bcoconni** [comment]
@BreakerHUN this bug should now be fixed in the `master` branch, following @AlbanBERGERET-Epic's PR #652. Could you please check and confirm if the plugin now works as expected ?

Thanks.

**Comment by BreakerHUN** [comment]
@bcoconni Thanks for the effort! I recompiled it and can confirm that the problem is now gone. It is now working properly.

One thing to mention, that it still crashes if you do not add a "georeferencing" object in the leveleditor, and hit "play" button. But that can be fixed easily. Might worth to handle this case with an error message and avoid running instead of crashing to desktop :) But this issue can be closed.

**Comment by bcoconni** [comment]
> @bcoconni Thanks for the effort! I recompiled it and can confirm that the problem is now gone. It is now working properly.

No, thanks @AlbanBERGERET-Epic who did all the hard work ! :+1: 

> One thing to mention, that it still crashes if you do not add a "georeferencing" object in the leveleditor, and hit "play" button. But that can be fixed easily. Might worth to handle this case with an error message and avoid running instead of crashing to desktop :) But this issue can be closed.

I'd suggest you open a new issue to report this problem.

Thanks for the bug report.
